image: alpine:3.10

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build-and-docker-release
  - update-docker-hub-readme

variables:
  DOCKER_REGISTRY_DOCKERHUB_REPO: "anacha/arm64v8-alpine-golang"
  TMPTAG: "1.13.2"

docker:release:
  stage: build-and-docker-release
  image: docker:latest
  allow_failure: false
  only:
  - master
  - dev
  tags:
    - aarch64
    - alpine
  services:
  - docker:dind
  cache: {}
  dependencies: []
  script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - >-
    docker build --pull
    -t $CI_REGISTRY_IMAGE:$TMPTAG
    -t $CI_REGISTRY_IMAGE:latest
    -t $DOCKER_REGISTRY_DOCKERHUB_REPO:$TMPTAG
    -t $DOCKER_REGISTRY_DOCKERHUB_REPO:latest
    .
  - docker images
  - echo "$CI_BUILD_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  - docker push $CI_REGISTRY_IMAGE:$TMPTAG
  - docker push $CI_REGISTRY_IMAGE:latest
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin "$DOCKERHUB_REGISTRY"
  - docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:$TMPTAG
  - docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:latest
  - docker logout "$CI_REGISTRY"
  - docker logout "$DOCKERHUB_REGISTRY"

docker:release-arm32v7:
  stage: build-and-docker-release
  image: docker:latest
  allow_failure: true
  only:
  - master
  - dev
  tags:
    - aarch64
    - alpine
  services:
  - docker:dind
  cache: {}
  dependencies: []
  script:
  - uname -m
  - apk --print-arch
  - docker run --rm --privileged multiarch/qemu-user-static:latest --reset -p yes
  - >-
    docker build --pull
    -t $CI_REGISTRY_IMAGE:$TMPTAG-arm32v7
    -t $CI_REGISTRY_IMAGE:latest-arm32v7
    -t $DOCKER_REGISTRY_DOCKERHUB_REPO:$TMPTAG-arm32v7
    -t $DOCKER_REGISTRY_DOCKERHUB_REPO:latest-arm32v7
    -f Dockerfile.arm32v7
    .
  - docker images
  - echo "$CI_BUILD_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  - docker push $CI_REGISTRY_IMAGE:$TMPTAG-arm32v7
  - docker push $CI_REGISTRY_IMAGE:latest-arm32v7
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin "$DOCKERHUB_REGISTRY"
  - docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:$TMPTAG-arm32v7
  - docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:latest-arm32v7
  - docker logout "$CI_REGISTRY"
  - docker logout "$DOCKERHUB_REGISTRY"

docker-hub:update-readme:
  stage: update-docker-hub-readme
  image: docker:latest
  variables:
    DOCKERHUB_REPO_PREFIX: "anacha"
    DOCKERHUB_REPO_NAME: "arm64v8-alpine-golang"
    DOCKER_REGISTRY_DOCKERHUB_REPO: "$DOCKERHUB_REPO_PREFIX/$DOCKERHUB_REPO_NAME"
  only:
  - master
  services:
  - docker:dind
  cache: {}
  dependencies: []
  script:
  - >-
    docker run --rm
    -v $(pwd)/README.md:/data/README.md
    -e DOCKERHUB_USERNAME="$DOCKERHUB_USERNAME"
    -e DOCKERHUB_PASSWORD="$DOCKERHUB_PASSWORD"
    -e DOCKERHUB_REPO_PREFIX="$DOCKERHUB_REPO_PREFIX"
    -e DOCKERHUB_REPO_NAME="$DOCKERHUB_REPO_NAME"
    sheogorath/readme-to-dockerhub
